### ISSUE TITLE
Compression increases filesize

### ISSUE THREAD

**Issue by sconeyard** [whitequark/ocaml-lz4#12]
I don't know if this is maintained anymore, but I'll try anyway. 

```
    let lines =  load_big_file file in
    Printf.printf "%S\n" (string_of_int (Bigarray.Array1.dim lines));
    let compressed_content = LZ4.Bigbytes.compress(lines) in
        Printf.printf "%S\n" (string_of_int (Bigarray.Array1.dim compressed_content));
        write compressed_content "file.ext";
```

Gives me:

"523283080"
"524743149"

I assume I did something wrong, as there is no such issue reported here. I pass a Bigarray to the compression function. I tested several files, yet not a single one decreases in size.

**Comment by whitequark** [comment]
I think it's your files. E.g.:
```
# LZ4.Bytes.compress (Bytes.of_string "aaaaaaaaaaaaaaaaaaaaaaaaaaaa");;
- : bytes = Bytes.of_string "\031a\001\000\003Paaaaa"
```
LZ4 is tuned for speed, not for compression ratio, so if you try to use it with high-entropy files this is what happens. Take a look at LZ4_HC.

**Comment by sconeyard** [comment]
Hmm, I see. I tried with constructed test files of repetitive strings, it works fine there. I just couldn't imagine my initial files to be such high-entropy. 

I'll check out LZ4_HC, thanks for the tip and your quick answer!
