### ISSUE TITLE
wouldn't it be possible to have a LZ4.uncompress_bound?

### ISSUE THREAD

**Issue by UnixJunkie** [whitequark/ocaml-lz4#13]
trying decompress with larger and larger ~length parameter to hold the output until it succeeds doesn't look very smart.
You already have a compress_bound, so I wonder if it is possible.

**Comment by whitequark** [comment]
Unfortunately not, this is a fundamental limitation of lz4 (and any other compression algorithm that does not store decompressed size in the stream). You can construct almost arbitrarily expanding strings (exponential with input size).

You're not supposed to store lz4 streams without also storing the decompressed size. It's a low-level building block.

**Comment by UnixJunkie** [comment]
Thank you very much for this critical piece of info: "You're not supposed to store lz4 streams without also storing the decompressed size". I had no idea about it.
