### ISSUE TITLE
Can't install on M1 Mac

### ISSUE THREAD

**Issue by syedtaz** [whitequark/ocaml-lz4#19]
Hello. I'm trying to install this package using OPAM and I get the following error if I run `opam install lz4`

```
File "lib_gen/dune", line 15, characters 9-18:
   2   │ 15 |   (names LZ4_stubs))
   3   │               ^^^^^^^^^
   4   │ (cd _build/default/lib_gen && /usr/bin/cc -O2 -fno-strict-aliasing -fwrapv -pthread -D_FILE_OFFSET_BITS=64 -O2 -fno-strict-aliasing -fwrapv -pthread -g -I /Users/taz/.opam/5.0.0/lib/ocaml -I /Users/taz/.opam/5.0.0/lib/bigarray-compat -I /Users/taz/.opam/5.0.0/lib/b
       │ ytes -I /Users/taz/.opam/5.0.0/lib/ctypes -I /Users/taz/.opam/5.0.0/lib/integers -I /Users/taz/.opam/5.0.0/lib/stdlib-shims -o LZ4_stubs.o -c LZ4_stubs.c)
   5   │ LZ4_stubs.c:1:10: fatal error: 'lz4.h' file not found
   6   │ #include <lz4.h>
   7   │          ^~~~~~~
   8   │ 1 error generated.
```

However, I do have the header files available under the homebrew folder. 
```
$ ls /opt/homebrew/opt/lz4/include/
lz4.h  lz4frame.h  lz4frame_static.h  lz4hc.h
```

I'm using an M1 Mac with OSX 13.0, Opam 2.1.4 and a switch with Ocaml 5.0. Do you have any ideas on what might help?

**Comment by actionshrimp** [comment]
I'd run into this before, so did a bit of digging here to try and understand the issue a bit better.

lz4 doesn’t use `pkg-config` or anything like that, and just adds -llz4 [to the c compilation flags](https://github.com/whitequark/ocaml-lz4/blob/master/lib_gen/dune#L16), so expects the rest of the env to be set up correctly so lz4 can be discovered in known paths (e.g. /opt/homebrew/{include,lib} for homebrew). 

On m1 mac homebrew doesnt set these up for some reason (not sure if/why this is different from non-m1 mac?) which leads to the errors doing opam install:

```
$ opam install lz4
...
# LZ4_stubs.c:1:10: fatal error: 'lz4.h' file not found
# #include <lz4.h>
#          ^~~~~~~
```
Setting `CPATH` gets you to:

```
$ CPATH=/opt/homebrew/include opam install lz4
# ld: library not found for -llz4
# clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

Which you can then get past by additionally setting `LIBRARY_PATH=/opt/homebrew/lib`:

```
$ CPATH=/opt/homebrew/include LIBRAR_PATH=/opt/homebrew/lib opam install lz4
...
⬇ retrieved lz4.1.2.0  (cached)
∗ installed lz4.1.2.0
Done.
```

You might also need to set `LD_LIBRARY_PATH=/opt/homebrew/lib` to avoid runtime errors? I haven’t checked this though.

**Comment by c-cube** [comment]
With #21 merged I think this is fixed.
