### ISSUE TITLE
decompress always create a 'storage'

### ISSUE THREAD

**Issue by UnixJunkie** [whitequark/ocaml-lz4#7]
this is bad for performance (you always allocate). Users should be allowed to pass a buffer, with an offset in it and a maximum size to use in it.

**Comment by UnixJunkie** [comment]
I won't send anymore code, no need to ask.

**Comment by whitequark** [comment]
I added `compress_into` and `decompress_into` interfaces.

**Comment by UnixJunkie** [comment]
thanks a lot !

**Comment by whitequark** [comment]
Are these sufficient for your needs?

**Comment by UnixJunkie** [comment]
I think so, I will test them soon

**Comment by UnixJunkie** [comment]
I am OK with the Bytes.compress_into and Bytes.decompress_into.
I'll switch to the Bigarray version soon.
